services:
  - type: web
    name: zentro-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: zentro-mongodb
          property: connectionString

databases:
  - name: zentro-mongodb
    databaseName: zentro
    plan: free
    user: zentro_user
    region: oregon 